apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-quarkus-native
spec:
  workspaces:
  - name: shared-workspace
  - name: maven-settings
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "main"
  - name: IMAGE
    type: string
    description: image to be build from the code
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-java
    taskRef:
      name: maven
      kind: ClusterTask
    params:
    - name: GOALS
      value: 
        - package
        - -Dquarkus.package.type=native-sources
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: maven-settings
      workspace: maven-settings
    runAfter:
    - fetch-repository
  - name: build-native
    taskRef:
      name: quarkus-native-build
      kind: Task
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - build-java
  - name: build-and-push-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: DOCKERFILE
      value: src/main/docker/Dockerfile.native
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - build-native
